### ISSUE TITLE
[BUG] web socket connection failed

### ISSUE THREAD

**Issue by NicolasPrr** [tokyapp/toky-phone-js-sdk#2]
Use the method  .init()  of Client appears doest not work, the  log in the console is ` toky-sdk-alpha.js:2 WebSocket connection to 'wss://sao3.beta.toky.co:10443/' failed: ` however  we can get information from  the API

**Comment by yoryer** [comment]
Hi @NicolasPrr 
There was an error retrieving the list of websocket servers available and the results were including a couple of servers that are not available anymore, the issue should be solved right now. Please just let us know if you still have this issue.

**Comment by dev-amirmalik** [comment]
Hi @yoryer 
I got same a issue with "WebSocket connection to 'wss://us-3.voip.toky.co:10443/' failed: ". Am I missed something?
I ran the example code from this repository and am still having the same issue.
