### ISSUE TITLE
websocket connection failed

### ISSUE THREAD

**Issue by dev-amirmalik** [tokyapp/toky-phone-js-sdk#3]
Hi @yoryer 

I tried to implement the SDK in my app, but I still got a connection failed code: 1006.
Before that, I tried to run the example app in this repository, but I still had an issue connecting to the Toky VoIP.

Evidence:
Chrome
![image](https://github.com/tokyapp/toky-phone-js-sdk/assets/167948835/47f8c0fd-f7a8-4875-bdbb-f3dd77fc4457)
![image](https://github.com/tokyapp/toky-phone-js-sdk/assets/167948835/6a23c344-0fbb-4926-aa1a-cf7def36310a)

Firefox
![image](https://github.com/tokyapp/toky-phone-js-sdk/assets/167948835/f17d7c98-409a-41d2-b891-bb30f3beede6)
![image](https://github.com/tokyapp/toky-phone-js-sdk/assets/167948835/4542314e-c84c-41a3-b300-9c9cb2f1ee60)

Am I missed something?

Thanks

**Comment by yoryer** [comment]
Hi @dev-amirmalik 
I suggest you get in touch through the support center so we can share confidential information there in case we need it to check your case.

**Comment by dev-amirmalik** [comment]
Hi @yoryer 
Yes you are right. You need to contact the support. Maybe the production has bugs or something that causing the issue.
Currently I can ues the sdk.

I close this issue.

Thanks
